language: node_js
node_js:
  - "node"
branches:
  only:
    - master
install:
  - yarn
script:
  - hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  fqdn: blog.rulelikewise.com
  on:
    branch: master
